const ACTIONS = {
    //entities
    GET_TODOLIST: 'GET_TODOS',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    LOADER_UP: 'LOADER_UP',
    LOADER_DOWN: 'LOADER_DOWN',

    //view
    SORT_ALL: 'SORT_ALL',
    SORT_A_Z: 'SORT_A_Z',
    SORT_Z_A: 'SORT_Z_A',
    SORT_DONE_UNDONE: 'SORT_DONE_UNDONE',
    SORT_UNDONE_DONE: 'SORT_UNDONE_DONE',
    FILTER_DONE: 'FILTER_DONE',
    FILTER_UNDONE: 'FILTER_UNDONE',
    SEARCH: 'SEARCH',
};

export default ACTIONS;
