const ACTIONS = {
    //entities
    GET_TODOLIST: 'GET_TODOS',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    EDIT_TODO: 'EDIT_TODO',
    LOADER_UP: 'LOADER_UP',
    LOADER_DOWN: 'LOADER_DOWN',
    CLEAR_ALL: 'CLEAR_ALL',
    SET_ERROR: 'SET_ERROR',
    SEARCH: 'SEARCH_TODO',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
};

export default ACTIONS;
